[package]
name = "stackline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn-clone = "1.0"
palette = "0.6"

[dev-dependencies]
colored = "2.0"
